type: sl
fps: 15
view: SIDE_BY_SIDE
resolution: VGA
depth_mode: ULTRA
max_depth: 3  # 3 meters

image_mapping:
  left: 'image.left'
  right: 'image.right'
  depth: 'image.depth'
  depth_mask: 'image.depth_mask'
