name: positronic
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - libstdcxx-ng>=12.1.0
  - gxx_linux-64
  - jupyter
  - numpy
  - matplotlib
  - rerun-sdk
  - flask
  - scipy
  - requests
  - fastapi
  - uvicorn
  - pip
  - pip:
    - dm_control
    # - franky-panda

    # - frankx
    # - https://artifactory.kinovaapps.com/ui/native/generic-public/kortex/API/3.3.0/kortex_api-3.3.0.2-py3-none-any.whl

  #   - isaacsim
  #   - isaacsim-kernel
  #   - isaacsim-app
  #   - isaacsim-asset
  #   - isaacsim-core
  #   - isaacsim-robot  # !!!!

  #   - isaacsim-robot-setup
  #   - isaacsim-sensor

  #   - isaacsim-robot-motion
  #   - isaacsim-template
  #   - isaacsim-test
  #   - isaacsim-utils
