name: positronic
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.11
  - libstdcxx-ng>=12.1.0
  - gxx_linux-64
  - jupyter
  - numpy
  - matplotlib
  - rerun-sdk
  - scipy
  - requests
  - fastapi
  - uvicorn[standard]
  - pymodbus
  - pytorch
  - pytorch3d
  - opencv
  - av
  - pip
  - pip:
    - pytest
    - lerobot
    - click
    - yappi
    - websockets
    - hydra-core
    - hydra-colorlog

# python /usr/local/zed/get_python_api.py