name: positronic
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  # Build tools
  - gcc_linux-64
  - gxx_linux-64
  # Deps
  - jupyter
  - numpy
  - matplotlib
  - rerun-sdk
  - scipy
  - requests
  - fastapi
  - uvicorn[standard]
  - pymodbus
  - pytorch
  - pytorch3d
  - opencv
  - av
  - pip
  - pip:
    - pytest
    - pytest-asyncio
    - lerobot
    - click
    - yappi
    - websockets
    - hydra-core
    - hydra-colorlog
    - dearpygui
    - robosuite
    - fire
# python /usr/local/zed/get_python_api.py
