name: positronic
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.11
  # Build tools
  - gcc_linux-64
  - gxx_linux-64
  # Deps
  - av
  - evdev
  - fastapi
  - jupyter
  - matplotlib
  - numpy
  - opencv
  - pymodbus
  - pytorch
  - pytorch3d
  - requests
  - rerun-sdk
  - scipy
  - uvicorn[standard]
  - pip
  - pyaudio
  - pip:
    - click
    - cmake-build-extension
    - dearpygui
    - fire
    - hydra-colorlog
    - hydra-core
    - lerobot
    - numpy-quaternion
    - pytest
    - pytest-asyncio
    - robosuite
    - websockets
    - yappi
    - dm_control
    - pyspacemouse
    - git+https://github.com/lilohuang/PyTurboJPEG.git@v1.7.8
    - linuxpy
# python /usr/local/zed/get_python_api.py
