_target_: inference.StateEncodingConfig
state_output_key: observation.state
images:
  - key: image.left
    output_key: observation.images.left
    resize: null
  - key: image.right
    output_key: observation.images.right
    resize: null
state:
  - robot_position_translation
  - robot_position_quaternion
  - robot_joints
  - ext_force_ee
  - ext_force_base
  - grip
