_target_: inference.StateEncodingConfig
state_output_key: observation.state
images:
  - key: image.front
    output_key: observation.images.front
    resize:
      - 352
      - 192
  - key: image.back
    output_key: observation.images.back
    resize:
      - 352
      - 192
state:
  - robot_position_translation
  - robot_position_quaternion
  - grip
