_target_: inference.StateEncodingConfig
images:
  - key: image.left
    output_key: image_wrist
    resize:
      - 128
      - 128

state_output_key: observation.state
state:
  - robot_position_translation
  - robot_position_quaternion
  - grip
