_target_: inference.StateEncodingConfig
state_output_key: observation.state
images:
  - key: image.left
    output_key: observation.images.left
    resize:
      - 352
      - 192
  - key: image.right
    output_key: observation.images.right
    resize:
      - 352
      - 192
state:
  - robot_position_translation
  - robot_position_quaternion
  - grip
