_target_: tools.inference.StateEncodingConfig
images:
  - key: left
    resize:
      - 352
      - 192
  - key: right
    resize:
      - 352
      - 192
state:
  - robot_position_translation
  - robot_position_quaternion
  - grip
