name: Check code style

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install black==25.1
    - name: Check code style for changed files
      run: |
        git diff --name-only --diff-filter=D origin/main HEAD | grep ".py$" | xargs -r black --check --diff --skip-string-normalization
