defaults:
  - state: tqg_352x192

rerun: None

franka:
    ip: 172.168.0.2
    relative_dynamics_factor: 0.2
    gripper_force: 0.4
    reporting_frequency: 30

inference:
  checkpoint_path: ???
  device: cuda

  state: ${state}

  action:
    - target_robot_position_trans
    - target_robot_position_quat
    - target_grip

