defaults:
  - state: tqg_352x192
  - action: baseline
  - hardware: franka_mujoco
  - _self_

rerun: null

inference:
  checkpoint_path: ???
  device: cuda

  inference_time_sec: 10

  state: ${state}
  action: ${action}

  rerun: true

policy_args:
  use_temporal_ensembler: false

image_name_mapping:
  front: handcam_front
  back: handcam_back

mujoco:
  camera_names:
    - handcam_front
    - handcam_back
