defaults:
  - camera: sl_vga15
  - _self_

webxr:
  port: 5005

franka:
  ip: "172.168.0.2"
  relative_dynamics_factor: 0.2
  gripper_force: 0.4

dh_gripper: "/dev/ttyUSB0"

data_output_dir: null

profile: false
