defaults:
  - state: tqg_352x192
  - action: absolute
  - _self_

input_dir: _dataset/
output_dir: ???

timestamp_units: 'ns'
start_from_zero: true

dataset:
  fps: 60
  video: true
  run_compute_stats: true
