defaults:
  - state: tqg_352x192
  - _self_

input_dir: _dataset/
output_dir: ???

action:
  - target_robot_position.translation
  - target_robot_position.quaternion
  - target_grip

dataset:
  fps: 12
  video: true
  run_compute_stats: true
